### ISSUE TITLE
[Crashes][WLAN][Jenkins] Jenkins Crashes

### ISSUE THREAD

**Issue by urain39** [alcove-sh/Alcove.sh#25]
Possible Exception

```log
java.net.SocketException: Permission denied
```

**Comment by urain39** [comment]
Looks like  Android permission limited the user to access to WLAN, so the solution is adding jenkins runner to related user group.

**Comment by uzilla** [comment]
May we should add a patch for `useradd`? i saw the `/etc/default/useradd` can change something default, but still cannot do that. So may we should just change `useradd`?

**Comment by urain39** [comment]
Just works, seems we need a patch.
